### ISSUE TITLE
Nee help wit gulp nav and nunjucks

### ISSUE THREAD

**Issue by furiousm** [jessaustin/gulp-nav#5]
Is IT possible to use this with nunjucks?

**Comment by jessaustin** [comment]
Like any other template system, *nunjucks* appears to take an [`env` object](http://mozilla.github.io/nunjucks/api.html#precompile) with whatever properties one needs. When using [gulp-nunjucks](https://github.com/sindresorhus/gulp-nunjucks), `env` comes from the *Vinyl* file object, as one would expect for any *gulp* plugin. If you need to see what data are being populated on the file object before it gets to *gulp-nunjucks*, use something like [through2-spy](https://github.com/brycebaril/through2-spy).

**Comment by furiousm** [comment]
Wow thank you for your time and answer. I did not expect to get a answer because my question leaks off the wright information. 

I've build a temperary sollution in using the gulp-pluck package and write an json file with al the yaml information from my templates. It's nice but not perfect.

Thanks for your answer with guiding to other packages to help me build the perfect gulp setup. I'm definitely going again use your package.

**Comment by furiousm** [comment]
get error, Cannot read property 'title' of null

var log = function(file, cb) {
  console.log(JSON.stringify(file,null,2));
  cb(null, file);
};

gulp.task("build", ["clean"], function() {
	return gulp.src('src/templates/**/*.njs')
		// Get data from a JSON file
		.pipe(data(function(file) {
			return {
				global: require('./src/data/global.json') 
			}
		}))
		.pipe(frontMatter({
			property: 'page'
		}))
		.pipe(nav())
		.pipe(map(log))
		.pipe(nunjucks({
			searchPaths: ['./src/'],
			ext: '.html',
			locals: {
				apiKey: 'secret-key-here'
			}
		}))
		.pipe(gulp.dest('build'));
});

Maybe, you cant get me in de wright direction again

**Comment by jessaustin** [comment]
I suspect that *nunjucks* doesn't know to look in either `nav` or `nav.data`, or (equivalently) you haven't specified the right `target` in your `nav()` call. Just insert the following everywhere, and you should see what's going on:
```javascript
require('through2-spy').obj(function (obj) { console.log(obj); });
```

**Comment by furiousm** [comment]
Thnx for the message, but i dont get it, pull my hairs off at the moment
My gulp file looks like this

```javascript

var gulp = require('gulp'),
	nunjucks = require('gulp-nunjucks-html'),
	data = require('gulp-data'),
	frontMatter = require('gulp-front-matter'),
	gutil = require('gulp-util'),
	rename = require('gulp-rename'),
	nav = require('gulp-nav'),
	path = require('path'),
	through = require('through2'),
	del = require('del'),
	plumber = require('gulp-plumber'),
	spy = require("through2-spy"),
	map = require('map-stream'),
	fs = require('vinyl-fs');

gulp.task('nav', function() {
    return gulp.src('src/templates/**/*.njs')
        .pipe(data(function(file) {
            return frontMatter(String(file.contents));
        }))
        .pipe(nav())
        .pipe(require('through2-spy').obj(function (obj) {
	    console.log(obj);
	}))
        .pipe(nunjucks({
	     searchPaths: ['./src/'],
	     ext: '.html',
	}))
        .pipe(gulp.dest('dist'));
});
```

terminal outputs

```
templates|⇒ gulp nav
[09:31:13] Working directory changed to ~/Sites/gulp/gulp-nunjucks
[09:31:13] Using gulpfile ~/Sites/gulp/gulp-nunjucks/gulpfile.js
[09:31:13] Starting 'nav'...
<File "colofon.njs" <Buffer 2d 2d 2d 0a 74 69 74 6c 65 3a 20 43 6f 6c 6f 66 6f 6e 0a 6f 72 64 65 72 3a 20 39 30 0a 2d 2d 2d 0a 0a 7b 25 20 65 78 74 65 6e 64 73 20 22 6c 61 79 6f ... >>
<File "contact.njs" <Buffer 2d 2d 2d 0a 74 69 74 6c 65 3a 20 43 6f 6e 74 61 63 74 0a 6f 72 64 65 72 3a 20 31 30 30 0a 2d 2d 2d 0a 0a 7b 25 20 65 78 74 65 6e 64 73 20 22 6c 61 79 ... >>
<File "home.njs" <Buffer 2d 2d 2d 0a 74 69 74 6c 65 3a 20 48 6f 6d 65 0a 6e 61 76 2e 74 69 74 6c 65 3a 20 48 6f 6d 65 0a 6f 72 64 65 72 3a 20 31 30 0a 2d 2d 2d 0a 0a 7b 25 20 ... >>
<File "nieuws.njs" <Buffer 2d 2d 2d 0a 74 69 74 6c 65 3a 20 4e 69 65 75 77 73 0a 68 61 73 5f 73 75 62 6e 61 76 3a 20 74 72 75 65 0a 6f 72 64 65 72 3a 20 32 30 0a 2d 2d 2d 0a 0a ... >>
<File "over.njs" <Buffer 2d 2d 2d 0a 74 69 74 6c 65 3a 20 4f 76 65 72 20 6d 69 6a 6e 20 68 6f 62 62 79 27 73 0a 6e 61 76 74 69 74 6c 65 3a 20 4f 76 65 72 0a 6f 72 64 65 72 3a ... >>
<File "video.njs" <Buffer 2d 2d 2d 0a 74 69 74 6c 65 3a 20 56 69 64 65 6f 0a 6f 72 64 65 72 3a 20 34 30 0a 2d 2d 2d 0a 0a 7b 25 20 65 78 74 65 6e 64 73 20 22 6c 61 79 6f 75 74 ... >>
<File "nieuws/nieuws-detail.njs" <Buffer 2d 2d 2d 0a 74 69 74 6c 65 3a 20 4e 69 65 75 77 73 20 64 65 74 61 69 6c 0a 6e 61 76 74 69 74 6c 65 3a 20 44 65 74 61 69 6c 0a 6f 72 64 65 72 3a 20 32 ... >>
[09:31:14] Finished 'nav' after 105 ms
```

**Comment by jessaustin** [comment]
By default *gulp-nav* populates `nav` and `data.nav`; this is mentioned toward the bottom of the main page. It seems that perhaps *nunjucks* is expecting `frontMatter` to be populated instead. To be sure, why don't you try this code instead?

```javascript
gulp.task('nav', function() {
    return gulp.src('src/templates/**/*.njs')
        .pipe(data(function(file) {
            return frontMatter(String(file.contents));
        }))
        .pipe(spy.obj(function (file) {
            console.log(file.frontMatter);
        }))
        .pipe(nav(targets='frontMatter'))
        .pipe(spy.obj(function (file) {
            console.log(file.frontMatter);
        }))
        .pipe(nunjucks({
         searchPaths: ['./src/'],
         ext: '.html',
        }))
        .pipe(gulp.dest('dist'));
});
```

**Comment by furiousm** [comment]
```javascript

		.pipe(fm({
			property: 'data.page'
		}))
```

this was the solution...

when use spy i get a error

```
title: nav.title undefined
```

**Comment by jessaustin** [comment]
ISTM these problems have little to do with the tools you're using and more to do with your understanding of the process of programming. *gulp* demands very little of its plugins. If a plugin handles a stream of vinyl objects `readable.pipe`d to it, and produces a stream of vinyl objects when `readable.pipe`d from, that's generally enough. Because of this, a programmer would know from the outset that the programmer herself bears responsibility for integrating *gulp-nav*, *gulp-nunjucks-html*, or anything else. The slogan is "garbage in, garbage out". These plugins will only do what you want if you give them what they require. Software doesn't read your mind. Even in your latest message, you display little understanding of the programming process.

Assuming `fm` refers to the [`gulp-front-matter` plugin](https://www.npmjs.com/package/gulp-front-matter) and not the [`front-matter` module](https://www.npmjs.com/package/front-matter), if telling it to look in `data.page` was the answer then this entire thread, which considered only things happening downstream from that plugin, was misdirected. Furthermore, *through2-spy* would not give you that error if you didn't specifically tell it to do something with `nav.title`. In future when you're having problems not with individual modules but with integrating them into your program, a random module's issue page probably won't be the best place to get help. You might try http://stackoverflow.com/.

**Comment by furiousm** [comment]
Thanks for your message, im a starter with gulp. but thanks for your help
