### ISSUE TITLE
Make parents with active children active too.

### ISSUE THREAD

**Issue by cato** [jessaustin/gulp-nav#8]
Hi,

Would it be possible for the parent of an active child to be classed as active too?

Cheers

**Comment by jessaustin** [comment]
Interesting suggestion! I think it's best that there is only one active element, but I can see that "parent of active" is also useful information. Would it be *more* useful to have "ancestor of active" instead? (Could be grandparent, etc.)

What would be a good single word to express this concept?

**Comment by cato** [comment]
Yep, ancestor of active is definitely more useful.

I think "active" is the term for the current page and all it's ancestors, and "current" is the current page.

**Comment by jessaustin** [comment]
Take a look at https://github.com/jessaustin/gulp-nav/tree/active-descendant

I've added a property called `hasActiveDescendant`. This means just what it says. I am kind of bummed to add the first compound-word property to this module, so I will happily consider other names for this concept.
